FROM node:latest

# Create app directory
WORKDIR /usr/app

# Copie o package.json e o package-lock.json
COPY ./package*.json ./
RUN npm install

# Copie o schema.prisma
COPY ./src/prisma/schema.prisma ./src/prisma/schema.prisma

# Copie o arquivo .env, se existir
RUN if [ -f .env ]; then cp .env .env; fi

# Gere o Prisma Client
RUN npx prisma generate

# Execute as migrações do Prisma e mantenha o contêiner em execução
CMD ["sh", "-c", "npx prisma migrate deploy && tail -f /dev/null"]