# Use a imagem base oficial do PostgreSQL
FROM postgres:latest

# Defina variáveis de ambiente padrão (opcional)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=pelika

# Copie arquivos de inicialização SQL ou scripts de configuração, se necessário
# COPY init.sql /docker-entrypoint-initdb.d/

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432